AWSTemplateFormatVersion: '2010-09-09'
Description: Template to Create an EC2 instance in an existing VPC
   
Parameters:

  ImageId:
    Type: String
    Description: 'Linux 2 AMI for north-virginia Region'
    Default: 'ami-0c2b8ca1dad447f8a'
  VpcId:
    Type: String
    Description: VPC id
    Default: vpc-0ff89b1a0cf9bc805
  SubnetId:
    Type: String
    Description: Subnet in which to launch an EC2
    Default: subnet-0ee8510f5bd7921c7
  AvailabilityZone:
    Type: String
    Description: Availability Zone into which instance will launch
    Default: us-east-1a
  InstanceType:
    Type: String
    Description: Choosing  t2 micro because it is free
    Default: t2.micro
  KeyName:
    Description: SSH Keypair to login to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: ec2-cft-key

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      AvailabilityZone: !Ref AvailabilityZone
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !Ref EC2SecurityGroup
      SubnetId: !Ref SubnetId

  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: SG to allow SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: SSH-sg

Outputs:
  DemoInstanceId:
    Description: Instance Id 
    Value: !Ref EC2Instance